<?php
/**
 * Custom Field
 * @author Indonez
 * @link http://indonez.com
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5643dfad028cd',
	'title' => 'Audio Format',
	'fields' => array (
		array (
			'key' => 'field_566fc4719c7b2',
			'label' => 'Audio Type',
			'name' => 'audio_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'self_hosted' => 'Self Hosted',
				'soundcloud' => 'Souncloud',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_5643dfb36e103',
			'label' => 'Audio URL',
			'name' => 'audio_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_566fc4719c7b2',
						'operator' => '==',
						'value' => 'self_hosted',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_566fc4fc8d86d',
			'label' => 'Soundcloud URL',
			'name' => 'soundcloud_url',
			'type' => 'oembed',
			'instructions' => 'Add soundcloud page URL here.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_566fc4719c7b2',
						'operator' => '==',
						'value' => 'soundcloud',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_format',
				'operator' => '==',
				'value' => 'audio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57616ff9cb32f',
	'title' => 'Gallery',
	'fields' => array (
		array (
			'key' => 'field_576178098bff3',
			'label' => 'Gallery Category',
			'name' => 'idz-gallery-category',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Category',
			'sub_fields' => array (
				array (
					'key' => 'field_5761788d45146',
					'label' => 'Gallery Name',
					'name' => 'idz-gallery-name',
					'type' => 'text',
					'instructions' => 'Please add your category name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_576178348bff4',
					'label' => 'Add Images',
					'name' => 'idz-category_images',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => '',
					'max' => '',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_576171e8486f0',
			'label' => 'Gallery Columns',
			'name' => 'idz-gallery-page-columns',
			'type' => 'radio',
			'instructions' => 'Please select default columns layout for gallery content',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'2columns' => '2 Columns',
				'3columns' => '3 Columns',
				'4columns' => '4 Columns',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_57618332e9aaf',
			'label' => 'Lightbox',
			'name' => 'idz-gallery-lightbox',
			'type' => 'radio',
			'instructions' => 'Enable or disable lightbox for gallery item',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'on' => 'On',
				'off' => 'Off',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'on',
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-gallery.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5643e9199e4f8',
	'title' => 'Gallery Format',
	'fields' => array (
		array (
			'key' => 'field_5643e91f86928',
			'label' => 'Gallery',
			'name' => 'gallery_set',
			'type' => 'gallery',
			'instructions' => 'Add a gallery by uploading multiple images here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_format',
				'operator' => '==',
				'value' => 'gallery',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5643e12f53626',
	'title' => 'Link Format',
	'fields' => array (
		array (
			'key' => 'field_5643e136961d4',
			'label' => 'Link URL',
			'name' => 'link_url',
			'type' => 'text',
			'instructions' => 'Add custom Link here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_format',
				'operator' => '==',
				'value' => 'link',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56430d76cb4bd',
	'title' => 'Page Options',
	'fields' => array (
		array (
			'key' => 'field_56430d90668d0',
			'label' => 'Page Layout',
			'name' => 'page_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'sidebar-right' => 'Right Sidebar',
				'no-sidebar' => 'No Sidebar',
				'sidebar-left' => 'Left Sidebar',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no-sidebar',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_56430eb2c66aa',
			'label' => 'Sidebar Widget',
			'name' => 'sidebar_widget',
			'type' => 'sidebar_selector',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56430d90668d0',
						'operator' => '!=',
						'value' => 'no-sidebar',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_null' => 1,
			'default_value' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56386f6fe5b95',
	'title' => 'Portfolio Options',
	'fields' => array (
		array (
			'key' => 'field_56386f86f2aa1',
			'label' => 'Lightbox URL',
			'name' => 'lightbox_url',
			'type' => 'text',
			'instructions' => 'Please enter image, youtube or vimeo url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56387142c23a8',
			'label' => 'Custom Link',
			'name' => 'custom_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Custom link portfolio item',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'indonez_portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5643e54a90b1e',
	'title' => 'Quote Format',
	'fields' => array (
		array (
			'key' => 'field_5643e551b718c',
			'label' => 'Quote Text',
			'name' => 'quote_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5643e565b718d',
			'label' => 'Quote Info',
			'name' => 'quote_info',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_format',
				'operator' => '==',
				'value' => 'quote',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5655501851600',
	'title' => 'Slideshow Options',
	'fields' => array (
		array (
			'key' => 'field_5655503d9534c',
			'label' => 'Enable Slider ?',
			'name' => 'enable_slider',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'no' => 'No',
				'yes' => 'Yes',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_565551b18ee8c',
			'label' => 'Slider',
			'name' => 'slider',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5655503d9534c',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_571a55d671ec8',
					'label' => 'Image',
					'name' => 'slider_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_571a55e771ec9',
					'label' => 'Content Type',
					'name' => 'slider_content_type',
					'type' => 'radio',
					'instructions' => 'Please select pre-defined text content for slider item',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'content-type-1' => 'Content Type 1',
						'content-type-2' => 'Content Type 2',
						'content-type-3' => 'Content Type 3',
						'content-type-4' => 'Content Type 4',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_571a561571eca',
					'label' => 'Slider Content Type 1',
					'name' => 'slider_content_type_1',
					'type' => 'textarea',
					'instructions' => 'You can modify the pre-defined text content for slider item from the default value',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_571a55e771ec9',
								'operator' => '==',
								'value' => 'content-type-1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<h1>Today Only!</h1>
                        <h2 class="discount-text1">up<br/>to</h2>
                        <h2 class="discount-text2">40</h2>
                        <h2 class="discount-text1"><span class="big-percent">%</span><br/>off</h2>
                        <h4>check it out, get inspired</h4>',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_571a563171ecb',
					'label' => 'Slider Content Type 2',
					'name' => 'slider_content_type_2',
					'type' => 'textarea',
					'instructions' => 'You can modify the pre-defined text content for slider item from the default value',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_571a55e771ec9',
								'operator' => '==',
								'value' => 'content-type-2',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<h1>Beautify the</h1>
                        <h2>atmosphere</h2>
                        <h4>makeover your living room with ease!</h4>
                        <a class="uk-button uk-button-small idz-button-outline uk-margin-medium-top" href="#">Discover Now</a>',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_571a565771ecc',
					'label' => 'Slider Content Type 3',
					'name' => 'slider_content_type_3',
					'type' => 'textarea',
					'instructions' => 'You can modify the pre-defined text content for slider item from the default value',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_571a55e771ec9',
								'operator' => '==',
								'value' => 'content-type-3',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<h1><span class="damion-font">Better Prices.</span></h1>
                        <h2>Bumper Choices.</h2>
                        <div class="uk-grid uk-grid-divider">
                    		<div class="uk-width-1-3 idz-number-wrap"><i class="uk-icon-thumbs-up"></i><h4>Best Product Quality</h4></div>
                    		<div class="uk-width-1-3 idz-number-wrap"><i class="uk-icon-trophy"></i><h4>Best Price Guaranteed</h4></div>
                    		<div class="uk-width-1-3 idz-number-wrap"><i class="uk-icon-truck"></i><h4>Express Delivery</h4></div>
                        </div>',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_571a567a71ecd',
					'label' => 'Slider Content Type 4',
					'name' => 'slider_content_type_4',
					'type' => 'textarea',
					'instructions' => 'You can modify the pre-defined text content for slider item from the default value',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_571a55e771ec9',
								'operator' => '==',
								'value' => 'content-type-4',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<h1><span>a spell of</span></h1>
                        <h2>Seating</h2>
                        <h4>up to 40% off</h4>
                        <a class="uk-button uk-button-small idz-button-grey uk-margin-medium-top" href="#">Shop Now</a>',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56330eb7db020',
	'title' => 'Team Options',
	'fields' => array (
		array (
			'key' => 'field_56330ecbe02db',
			'label' => 'Occupation',
			'name' => 'occupation',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Please enter the job position at the company',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56330f80d575a',
			'label' => 'Facebook',
			'name' => 'facebook',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Please enter facebook profile URL',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56330fcb0928a',
			'label' => 'Twitter',
			'name' => 'twitter',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Please enter twitter profile URL',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56331061dd430',
			'label' => 'Google+',
			'name' => 'google',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Please enter google+ profile URL',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5633113bd7234',
			'label' => 'Other Social Profile',
			'name' => 'other_social_profile',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Social Profile',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_5633128449500',
					'label' => 'Social Network',
					'name' => 'social_network',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Behance' => 'Behance',
						'Dribbble' => 'Dribbble',
						'Flickr' => 'Flickr',
						'Github' => 'Github',
						'Instagram' => 'Instagram',
						'Linkedin' => 'Linkedin',
						'Pinterest' => 'Pinterest',
						'Soundcloud' => 'Soundcloud',
						'Tumblr' => 'Tumblr',
						'Youtube' => 'Youtube',
						'Vimeo' => 'Vimeo',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_563312cc1198b',
					'label' => 'Profile URL',
					'name' => 'profile_url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'indonez_team',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56341ddc86e81',
	'title' => 'Testimonial Options',
	'fields' => array (
		array (
			'key' => 'field_56341de9f2ac5',
			'label' => 'Info',
			'name' => 'info',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Information text',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'indonez_testimonial',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5643dd43480ca',
	'title' => 'Video Format',
	'fields' => array (
		array (
			'key' => 'field_566fcc83eacff',
			'label' => 'Video Type',
			'name' => 'video_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'self_hosted' => 'Self Hosted',
				'yv_video' => 'Youtube or Vimeo',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_5643dd464b760',
			'label' => 'Video URL',
			'name' => 'video_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_566fcc83eacff',
						'operator' => '==',
						'value' => 'self_hosted',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_566fcd12782b1',
			'label' => 'Youtube or Vimeo',
			'name' => 'youtube_or_vimeo',
			'type' => 'oembed',
			'instructions' => 'Add your video url here, eg. page url from youtube, vimeo, etc.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_566fcc83eacff',
						'operator' => '==',
						'value' => 'yv_video',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_format',
				'operator' => '==',
				'value' => 'video',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

/* Add-Ons
 * USING PREMIUN ADD-ONS OUTSIDE THIS THEME IS NOT ALLOWED!!!
 */
add_filter('acf/settings/show_admin', '__return_false');
?>